import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Comic Neue', 'Comic Sans MS', 'cursive', 'sans-serif'],
        mono: ['Comic Neue', 'Comic Sans MS', 'ui-monospace', 'monospace'],
      },
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        'bg-primary': 'var(--bg-primary)',
        'bg-secondary': 'var(--bg-secondary)',
        'bg-tertiary': 'var(--bg-tertiary)',
        'text-primary': 'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'text-muted': 'var(--text-muted)',
        'success': 'var(--success)',
        'success-dark': 'var(--success-dark)',
        'warning': 'var(--warning)',
        'warning-dark': 'var(--warning-dark)',
        'error': 'var(--error)',
        'error-dark': 'var(--error-dark)',
        'info': 'var(--info)',
        'info-dark': 'var(--info-dark)',
        'sol': 'var(--sol)',
        'sol-dark': 'var(--sol-dark)',
        'quest': 'var(--quest)',
        'quest-dark': 'var(--quest-dark)',
        'gold': 'var(--gold)',
        'gold-dark': 'var(--gold-dark)',
        'gold-light': 'var(--gold-light)',
        'winner': 'var(--winner)',
        'cq-primary-green': '#23740D',
        'cq-primary-blue': '#74FDE7',
        'cq-primary-yellow': '#FFB84A',
        'cq-secondary-green': '#1EA495',
        'cq-secondary-yellow': '#E7EF88',
        'cq-success-green': '#89d005',
        'cq-neon': 'var(--gold)',
        'cq-gold': 'var(--gold)',
        'cq-cyan': 'var(--info)',
        'cq-bg-0': 'var(--bg-primary)',
        'cq-bg-1': 'var(--bg-secondary)',
        'cq-bg-2': 'var(--bg-tertiary)',
      },
      borderRadius: {
        'sm': 'var(--radius-sm)',
        'md': 'var(--radius-md)',
        'lg': 'var(--radius-lg)',
        'xl': 'var(--radius-xl)',
        'full': 'var(--radius-full)',
      },
      boxShadow: {
        'card': 'var(--shadow-card)',
        'button': 'var(--shadow-button)',
        'cabinet': 'var(--shadow-cabinet)',
        'glow-blue': 'var(--shadow-glow-blue)',
        'glow-purple': 'var(--shadow-glow-purple)',
        'glow-gold': 'var(--shadow-glow-gold)',
      },
    },
  },
  plugins: [],
};
export default config;
